= Starting a BFT node

BFT is an acronym for Byzantine Fault Tolerant
(link:https://eprint.iacr.org/2018/1049.pdf[Ouroboros-BFT:A Simple Byzantine Fault Tolerant Consensus Protocol]).

Jormungandr allows you to start a BFT blockchain fairly easily. This is designed for scenarios whereby expensive decentralised consensus isn't needed, such as within a company or other types of centrally controlled environments. In BFT mode only a few blessed nodes have the ability to create blocks.

== How does BFT work?

A given number of `nodes` (`N`) will each generate a key pair of type `Ed25519` (see
link:/httyj/#_key_subcommand[JCLI's Keys]).

Each node's public key is added to the `genesis.yaml` file, thus every BFT node is aware of every other node.
The genesis file is the single source of truth and will be used to generate the first block of the blockchain, that being; *Block-0*.

After the commencing of the blockchain, each BFT node takes turns, round robin fashion, creating blocks as ordered in the `genesis.yaml` file.

== Example of genesis file

[source, yaml]
----
blockchain_configuration:
  block0_date: 1550822014
  discrimination: test
  block0_consensus: bft
  slots_per_epoch: 5
  slot_duration: 15
  epoch_stability_depth: 10
  consensus_genesis_praos_active_slot_coeff: 0.22
  consensus_leader_ids:
    - ed25519e_pk1k3wjgdcdcn23k6dwr0cyh88ad7a4ayenyxaherfazwy363pyy8wqppn7j3
    - ed25519e_pk13talprd9grgaqzs42mkm0x2xek5wf9mdf0eefdy8a6dk5grka2gstrp3en
  allow_account_creation: true
  linear_fees:
    constant: 0
    coefficient: 0
    certificate: 0
initial_funds:
  - address: ta1svy0mwwm7mdwcuj308aapjw6ra4c3e6cygd0f333nvtjzxg8ahdvxlswdf0
    value: 10000
----

In order to start your blockchain in BFT mode you need to be sure that:

* `consensus_leader_ids` is non empty;

more information regarding the link:/httyj/#_the_genesis_file_for_your_permissioned_network[genesis file here].

== Creating the block-0

[source, bash]
----
jcli genesis encode --input genesis.yaml --output block-0.bin
----

This command will create (or replace) the **Block 0** of the blockchain
from the given genesis configuration file (`genesis.yaml`).

== Starting the node

Now that the blockchain is initialized, you need to start your node.

Write you private key in a file on your HD:

[source, bash]
----
$ cat node_secret.yaml
bft:
  signing_key: ed25519_sk1hpvne...
----

Configure your Node (config.yml) and run the following command:

[source, bash]
----
$ jormungandr --genesis-block block-0.bin \
    --config example.config \
    --secret node_secret.yaml
----

It's possible to use the flag `--secret` multiple times to run a node
with multiple leaders.

== Step by step to start the BFT node

* Generate initial config
[source, bash]
----
$ jcli genesis init > genesis.yaml`
----
* Generate secret key, e.g.
[source, bash]
----
$ jcli key generate --type=Ed25519 > key.prv
----
* Put secret key in a file, e.g. `node_secret.yaml` as follows:
[source, yaml]
----
bft:
 signing_key: ed25519_sk1kppercsk06k03yk4qgea....
----
* Generate public key out of previously generated key
[source, bash]
----
$ cat key.prv |  jcli key to-public
----
* Put generated public key in `genesis.yaml` under `consensus_leader_ids:`
* Generate block =
[source, bash]
----
$ jcli genesis encode --input genesis.yaml --output block-0.bin
----
* Create config file and store it on your HD as `node.config` e.g. ->

[source, yaml]
----
---
logger:
 verbosity: 4
 format: json
rest:
 listen: "127.0.0.1:8607"
 prefix: api
peer_2_peer:
 public_address: /ip4/127.0.0.1/tcp/8606
 topics_of_interests:
 messages: low
 blocks: normal
----

Start Jörmungandr node :
[source, bash]
----
$ jormungandr --genesis-block block-0.bin --config node.config --secret node_secret.yaml
----
